# NAME := libft.a
# CC := cc
# CFLAGS := -Wall -Wextra -Werror
# SRCS = ft_calloc.c ft_bzero.c ft_memset.c ft_strdup.c ft_strlen.c
# OBJS = $(SRCS: .c = .o)

# all : $(NAME)

# $(NAME) : $(OBJS)
# 	ar rcs $(OBJS) $(NAME)

# $(OBJS) : $(SRCS)
# 	$(CC) $(CFLAGS) $(SRCS) -c

# clean :
# 	rm -f $(OBJS)

# fclean : clean
# 	rm -f $(NAME)

# re : fclean all
